[theme]
# Primary color (Jemon: slider, button er background, active elements)
primaryColor = "#FF4B4B"

# App er main background color
backgroundColor = "#0D1137"

# Secondary background color (Jemon: sidebar, text input box)
secondaryBackgroundColor = "#FFFFFF"

# Text er color
textColor = "#31333F"

# Font style (Options: "sans serif", "serif", "monospace")
font = "sans serif"
