[theme]
# Primary color (Button, slider, active elements-er jonno bright color)
primaryColor = "#1E88E5"

# App er main background color (Ghor Alok ba Dark dark black/grey)
backgroundColor = "#0E1117"

# Secondary background color (Sidebar ba input box er background)
secondaryBackgroundColor = "#262730"

# Text er color (Sada ba halka grey jate porte subidha hoy)
textColor = "#FAFAFA"

# Font style
font = "sans serif"
